### ISSUE TITLE
the 3D data

### ISSUE THREAD

**Issue by lkf1996** [topcoderinc/Urban3d#3]
may I ask if the  dataset of the USSOCOM 3D challenge has been canceled in spacenet?

**Comment by goldbhr1** [comment]
Apologies for not seeing this issue from last year. Sorry about that. Yes, it is still there. However, it moved buckets but the links weren't updated on the SpaceNet page.

The new bucket is: s3://spacenet-dataset/Hosted-Datasets/Urban_3D_Challenge/.
