### ISSUE TITLE
Dataset links not working

### ISSUE THREAD

**Issue by RaagaMadappa** [topcoderinc/Urban3d#4]
Is this dataset still available? None of the links mentioned in the ReadMe file are working

**Comment by goldbhr1** [comment]
Sorry about that. Yes, it is still there. However, it moved recently but the links weren't updated on the SpaceNet page. 

The new bucket is: s3://spacenet-dataset/Hosted-Datasets/Urban_3D_Challenge/. 

I have reached out to the SpaceNet folks to have this updated on their website.
